import {
  ENCODING_EXECUTION_MESSAGES,
  INPUT_EXECUTION_MESSAGES,
  JWT_EXECUTION_MESSAGES,
} from "../../lib/devtools/shared/execution-messages.ts";
import type { ToolSpec } from "../../lib/tool-framework/spec";

export default {
  messages: {
    ...ENCODING_EXECUTION_MESSAGES,
    ...INPUT_EXECUTION_MESSAGES,
    ...JWT_EXECUTION_MESSAGES,
    "execution.token": "Token",
    "execution.length": "Length",
    "execution.errors.authorization-header-required": "Authorization header must start with Bearer.",
    "execution.recovery.authorization-header-required": "Paste the whole Authorization header or choose Raw token.",
    "execution.errors.token-required": "Bearer token is required.",
    "execution.recovery.token-required": "Paste the token itself, not just the Bearer prefix.",
    "workspace.algorithm_and_token_b36ea4": "Algorithm and token metadata",
    "workspace.claims_supplied_by_6cc4c4": "Claims supplied by the token",
    "workspace.field_f45fc1": "Field",
    "workspace.value_8e3795": "Value",
    "workspace.no_claims_96fbdb": "No claims.",
    "workspace.jwt_decoded_0d82e9": "JWT decoded",
    "workspace.token_extracted_27065a": "Token extracted",
    "workspace.header_and_payload_fa6f01": "Header and payload decoded. Signature not verified.",
    "workspace.token_content_has_4b4a3c": "Token content has not been decoded.",
    "workspace.extracted_token_5ea203": "Extracted token",
    "workspace.copy_length_fe45ee": "Copy length",
    "workspace.copy_token_d35b4e": "Copy token",
    "workspace.parts.Header": "Header",
    "workspace.parts.Payload": "Payload",
    "workspace.decoded.Header": "Decoded header",
    "workspace.decoded.Payload": "Decoded payload",
    "workspace.copyJson.Header": "Copy header JSON",
    "workspace.copyJson.Payload": "Copy payload JSON",
    "workspace.claimsLabel.Header": "Header claims",
    "workspace.claimsLabel.Payload": "Payload claims",
    "workspace.tokenPreview": "Token preview",
    "workspace.characterCount": "{count, plural, one {# character} other {# characters}}",
    "workspace.claims.alg": "Signing algorithm",
    "workspace.claims.typ": "Token type",
    "workspace.claims.kid": "Key ID",
    "workspace.claims.iss": "Issuer",
    "workspace.claims.sub": "Subject",
    "workspace.claims.aud": "Audience",
    "workspace.claims.exp": "Expires at (Unix seconds)",
    "workspace.claims.nbf": "Not valid before (Unix seconds)",
    "workspace.claims.iat": "Issued at (Unix seconds)",
    "workspace.claims.jti": "Token ID",
  },
  toolId: "devtools.bearer-token-parser",
  app: "devtools",
  category: "jwt-api-tools",
  keywords: ["bearer", "token", "authorization header", "jwt", "decode", "oauth"],
  name: "Bearer Token Parser",
  description: "Extract a Bearer token and decode it when it is a JWT.",
  layout: "stacked",
  resultView: { default: "preview" },
  input: {
    kind: "fields",
    label: "Authorization header or raw token",
    fields: [
      {
        channel: "text",
        label: "Authorization header or raw token",
        placeholder: "Bearer eyJhbGciOiJub25lIn0.eyJzdWIiOiIxMjMifQ.",
        required: true,
        multiline: true,
      },
    ],
  },
  settings: {
    fields: {
      inputFormat: {
        kind: "select",
        label: "Input format",
        help: "Detect either form, or require a Bearer header or raw token.",
        default: "auto",
        choices: [
          { label: "Auto-detect", value: "auto" },
          { label: "Authorization header", value: "header" },
          { label: "Raw token", value: "raw" },
        ],
      },
      decodeJwtParts: {
        kind: "toggle",
        label: "Decode JWT parts",
        help: "Decode three-part JWT headers and payloads as JSON.",
        default: true,
      },
      maskRawToken: {
        kind: "toggle",
        label: "Mask raw token",
        help: "Replace the token itself with bullets in visible output.",
        default: false,
      },
    },
  },
  trigger: { mode: "manual", actionLabel: "Parse token" },
  capabilities: { copy: true },
  workbenchMark: { text: "BEAR" },
  labels: {
    empty: "Enter an Authorization header or raw bearer token to parse it.",
    ready: "Parsed bearer token details are ready.",
    running: "Parsing bearer token…",
  },
  content: {
    howToUse: [
      "Paste either a whole Authorization header or just the token — the Bearer prefix is stripped for you, case-insensitively.",
      "Parse. If the token is a three-part JWT, you get its decoded header and payload as JSON alongside the token itself.",
      "If it is an opaque token, you get the token and its length, which is usually enough to tell one credential format from another.",
    ],
    limitations: [
      "The signature is decoded but never verified. A decoded payload proves nothing about authenticity — treat every claim as unverified.",
      "Only the JWS compact form is understood. Encrypted (JWE) and non-three-part tokens fall back to the opaque summary.",
      "The token is a live credential. Anything you paste here is shown back to you in full, so do not screenshot or share the result.",
    ],
    faq: [
      {
        q: "Does this validate the signature?",
        a: "No. Decoding a JWT is just Base64URL — it requires no key. Verification must happen server-side with the issuer's key.",
      },
      {
        q: "Is my token sent anywhere?",
        a: "No. Parsing happens entirely in this browser tab, and the token is not persisted between runs.",
      },
      {
        q: "Why does my token come back as opaque?",
        a: "Because it does not have exactly three dot-separated parts. Opaque access tokens from OAuth providers are random strings with no readable structure.",
      },
    ],
    examples: [
      {
        label: "Bearer header with a JWT",
        text: "Bearer eyJhbGciOiJub25lIn0.eyJzdWIiOiIxMjMifQ.",
      },
    ],
  },
} as const satisfies ToolSpec;
