import { COLOR_MESSAGES } from "../../lib/devtools/shared/color-messages.ts";
import type { ToolSpec } from "../../lib/tool-framework/spec";

export default {
  messages: {
    ...COLOR_MESSAGES,
    "workspace.gradient_preview_201b51": "Gradient preview",
    "workspace.reset_daee76": "Reset",
    "workspace.live_gradient_preview_59c765": "Live gradient preview",
    "workspace.select_a_stop_796479": "Select a stop, then adjust its color and position.",
    "workspace.correct_the_selected_d845b2": "Correct the selected color to restore the preview.",
    "workspace.use_these_colors_ee98d2": "Use these colors",
    "workspace.css_b581e4": "CSS",
    "workspace.preset_7252e7": "Preset",
    "workspace.custom_494ca7": "Custom",
    "workspace.type_baaddf": "Type",
    "workspace.linear_e6950b": "Linear",
    "workspace.radial_02693d": "Radial",
    "workspace.angle_196803": "Angle",
    "workspace.shape_e0e492": "Shape",
    "workspace.circle_b93d3b": "Circle",
    "workspace.ellipse_cb1ee8": "Ellipse",
    "workspace.center_d94606": "Center",
    "workspace.color_stops_f4d034": "Color stops · ",
    "workspace.add_9fd728": "Add",
    "workspace.editing_fab453": "Editing",
    "workspace.selected_stop_color_fa9570": "Selected stop color",
    "workspace.stop_position_a2b6f9": "Stop position",
    "workspace.reverse_gradient_9d7833": "Reverse gradient",
    "workspace.include_solid_color_c5bb47": "Include solid-color fallback",
    "workspace.drag_handles_or_6b416f":
      "Drag handles or press Space, use arrow keys, and press Space again to reorder stops.",
    "workspace.gradient": "Gradient",
    "workspace.presets.Blue to purple": "Blue to purple",
    "workspace.presets.Sunset": "Sunset",
    "workspace.presets.Ocean": "Ocean",
    "workspace.centerValue": "Center {axis} value",
    "workspace.gradientStops": "Gradient stops",
    "workspace.colorStop": "Color stop at {position}%",
    "workspace.reorderStop": "Reorder color stop at {position}%",
    "workspace.removeStop": "Remove color stop at {position}%",
    "workspace.stopCount": "Color stops {count}/12",
  },
  toolId: "devtools.gradient-generator",
  sharing: { version: 1 },
  app: "devtools",
  category: "color-design-tools",
  keywords: ["gradient", "css", "linear-gradient", "radial-gradient", "color", "background", "design"],
  name: "Gradient Generator",
  description: "Generate linear or radial CSS gradients.",
  outputLanguage: "css",
  input: {
    kind: "fields",
    label: "Gradient colors",
    fields: [
      {
        channel: "text",
        label: "Start color",
        placeholder: "#2563eb",
        required: true,
        maxLength: 100,
      },
      {
        channel: "secondary",
        label: "End color",
        placeholder: "#7c3aed",
        required: true,
        maxLength: 100,
      },
    ],
  },
  settings: {
    fields: {
      stops: { kind: "textarea", label: "Color stops", default: "", help: "Visual color-stop editor data." },
      radialShape: {
        kind: "select",
        label: "Radial shape",
        default: "circle",
        choices: [
          { label: "Circle", value: "circle" },
          { label: "Ellipse", value: "ellipse" },
        ],
      },
      radialX: { kind: "number", label: "Center X", default: 50, min: 0, max: 100, suffix: "%" },
      radialY: { kind: "number", label: "Center Y", default: 50, min: 0, max: 100, suffix: "%" },
      type: {
        kind: "select",
        label: "Gradient type",
        help: "Linear runs along an angle; radial spreads outward from the centre.",
        default: "linear",
        choices: [
          { label: "Linear", value: "linear" },
          { label: "Radial", value: "radial" },
        ],
      },
      angle: {
        kind: "number",
        label: "Angle",
        help: "0deg points up, 90deg points right. Ignored by a radial gradient.",
        default: 135,
        min: 0,
        max: 360,
        suffix: "deg",
        visibleWhen: { key: "type", equals: "linear" },
      },
      includeFallback: {
        kind: "toggle",
        label: "Include fallback",
        help: "Adds the start color before the gradient for unsupported browsers.",
        default: false,
      },
    },
  },
  trigger: { mode: "live", debounceMs: 160 },
  capabilities: { copy: true, download: true },
  workbenchMark: { text: "GRAD" },
  labels: {
    empty: "Enter two HEX colors to build a CSS gradient.",
    ready: "CSS gradient is ready.",
    running: "Generating CSS gradient…",
  },
  content: {
    howToUse: [
      "Enter the start and end colors as HEX. Short forms work too: #RGB, #RGBA, #RRGGBB, and #RRGGBBAA are all accepted.",
      "Pick linear or radial. For linear, set the angle — 0deg runs bottom to top, 90deg runs left to right, 180deg runs top to bottom.",
      "The declaration regenerates as you type, so you can nudge the angle and watch the result rather than guessing.",
      "Copy the finished `background:` line straight into your stylesheet.",
    ],
    limitations: [
      "Use up to 12 color stops. Repeating and conic gradients are not supported.",
      "Colors accept HEX, supported CSS names, rgb(), and hsl(). CSS variables are not resolved.",
      "Radial gradients support circle or ellipse shapes and a custom center; sizing keywords use browser defaults.",
      "No vendor prefixes are emitted. None are needed by any browser still receiving security updates.",
    ],
    faq: [
      {
        q: "Which way does the angle point?",
        a: "CSS angles are measured clockwise from pointing up, so 0deg goes bottom to top, 90deg goes left to right, and 180deg goes top to bottom.",
      },
      {
        q: "Can I use transparency?",
        a: "Yes. Use the eight-digit #RRGGBBAA form — for example #2563eb00 for a fully transparent blue that fades cleanly.",
      },
      {
        q: "Why does the angle field disappear?",
        a: "A radial gradient has no direction, so the angle is hidden rather than shown as a control that does nothing.",
      },
      {
        q: "Why does my fade to transparent look grey?",
        a: "Fading to plain `transparent` interpolates through transparent black. Fade to the same colour with alpha 00 instead, which is what the #RRGGBBAA form gives you.",
      },
    ],
    examples: [
      {
        label: "Blue to purple",
        text: "#2563eb",
        secondary: "#7c3aed",
        settings: { stops: "", type: "linear", angle: 135, radialShape: "circle", radialX: 50, radialY: 50 },
      },
    ],
  },
} as const satisfies ToolSpec;
