import { COLOR_MESSAGES } from "../../lib/devtools/shared/color-messages.ts";
import type { ToolSpec } from "../../lib/tool-framework/spec";

export default {
  messages: {
    "contrast.ratio": "Contrast ratio",
    "contrast.displayedText": "Displayed text",
    "contrast.displayedBackground": "Displayed background",
    "contrast.pass": "Pass",
    "contrast.fail": "Fail",
    "contrast.aaPass": "AA normal text passes",
    "contrast.aaFail": "AA normal text fails",
    "contrast.canvasOpaque": "Canvas color must be opaque to measure transparency.",
    "contrast.check.0": "AA · normal text",
    "contrast.check.1": "AA · large text",
    "contrast.check.2": "AAA · normal text",
    "contrast.check.3": "AAA · large text",
    ...COLOR_MESSAGES,
    "workspace.text_contrast_8cdead": "Text contrast",
    "workspace.wcag_2_contrast_2df30a": "WCAG 2 contrast ratio",
    "workspace.aa_normal_text_feedfb": "AA normal text passes",
    "workspace.aa_normal_text_155fc3": "AA normal text fails",
    "workspace.preview_heading_4a0861": "Preview heading",
    "workspace.preview_body_text_46356b": "Preview body text",
    "workspace.contrast_checks_06afb9": "Contrast checks",
    "workspace.minimum_3e72fb": "Minimum ",
    "workspace.pass_ebdf8c": "Pass",
    "workspace.fail_09230b": "Fail",
    "workspace.large_text_24px_61dfed":
      "Large text: 24px or larger; bold text: 18.67px or larger. Pass/fail uses the full precision ratio.",
    "workspace.text_color_4a69d0": "Text color",
    "workspace.swap_text_and_ead1c1": "Swap text and background",
    "workspace.background_color_3e314d": "Background color",
    "workspace.find_a_passing_0f1b5c": "Find a passing text color",
    "workspace.canvas_behind_transparency_1dcdfd": "Canvas behind transparency",
    "workspace.use_an_opaque_e39511": "Use an opaque color. Transparent layers are composited over this surface.",
    "workspace.colorPair": "Color pair",
    "workspace.checks.0": "AA · normal text",
    "workspace.checks.1": "AA · large text",
    "workspace.checks.2": "AAA · normal text",
    "workspace.checks.3": "AAA · large text",
    "workspace.minimumRatio": "Minimum {value}:1",
    "workspace.opaqueCanvas": "Canvas color must be opaque to measure transparency.",
    "workspace.invalidColor": "Enter a valid foreground, background, and canvas color.",
  },
  toolId: "devtools.contrast-checker",
  sharing: { version: 1 },
  app: "devtools",
  category: "color-design-tools",
  name: "Contrast Checker",
  description: "Check text contrast, preview readable combinations, and find an accessible foreground color.",
  keywords: ["color", "contrast", "accessibility", "WCAG", "AA", "AAA"],
  input: { kind: "none" },
  settings: {
    fields: {
      foreground: { kind: "text", label: "Text color", default: "#334155", maxLength: 200 },
      background: { kind: "text", label: "Background", default: "#FFFFFF", maxLength: 200 },
      canvas: { kind: "text", label: "Canvas behind transparency", default: "#FFFFFF", maxLength: 200 },
      sample: { kind: "text", label: "Preview heading", default: "Good design is easy to read.", maxLength: 160 },
      bodySample: {
        kind: "text",
        label: "Preview body text",
        default:
          "This is normal-size text. Check headings, descriptions, and everyday reading against the background you actually use.",
        maxLength: 1000,
      },
    },
  },
  trigger: { mode: "live", debounceMs: 100 },
  capabilities: { copy: true, download: true },
  workbenchMark: { text: "AA" },
  labels: {
    empty: "Choose your text and background colors.",
    ready: "Contrast measured.",
    running: "Measuring contrast…",
  },
  content: {
    howToUse: [
      "Choose text and background colors or paste HEX, RGB, HSL, or a CSS name.",
      "Compare the ratio with the AA and AAA thresholds. Alpha is composited over the opaque canvas color.",
      "Try a suggested foreground, swap colors, or copy the report.",
    ],
    limitations: [
      "Measures WCAG 2 contrast for solid sRGB colors. Images, gradients, blend modes, and font rendering are not evaluated.",
      "Large text means at least 24 CSS px, or about 18.67 CSS px when bold. A passing color pair alone does not establish page accessibility.",
    ],
    relatedToolIds: ["devtools.color-picker", "devtools.palette-generator", "devtools.color-converter"],
  },
} as const satisfies ToolSpec;
