import type { ToolSpec } from "../../lib/tool-framework/spec";

export default {
  messages: {
    "image.missing": "Choose an image to sample its colors.",
    "image.unsupported": "Choose a PNG, JPEG, WebP, or GIF image.",
    "image.size": "Choose a nonempty image smaller than 20 MB.",
    "image.canvas": "Image sampling is unavailable in this browser.",
    "image.decode": "This image could not be read. Try another image or export it as PNG.",
    "image.dimensions": "Choose an image with no more than 24 million pixels.",
    "image.width": "Width",
    "image.height": "Height",
    "image.pixel": "Selected pixel",
    "image.pixelLabel": "Pixel",
    "image.palette": "Approximate palette",
    "image.visibleShare": "Visible share",
    "image.controlTitle": "Pick a pixel",
    "image.uploadHint": "Click to choose, or drop an image. Nothing is uploaded.",
    "image.selection": "{width} × {height} pixels · Selected {x}, {y}",
    "image.selectedPixel": "Selected pixel {hex}",
    "image.transparency": "Transparency background",
    "image.pickerHelp":
      "Image color picker. Click or drag to select a pixel. Arrow keys move one pixel; hold Shift to move ten.",
    "workspace.image_1aa4cb": "Image",
    "workspace.upload_865e89": "Upload",
    "workspace.png_jpeg_webp_601a79": "PNG · JPEG · WebP · GIF · up to 20 MB",
    "workspace.pick_colors_from_8c65bb": "Pick colors from an image",
    "workspace.upload_another_image_2549e7": "Upload another image to try again.",
    "workspace.reading_the_image_9a0944": "Reading the image…",
    "workspace.click_or_drag_945c3c":
      "Click or drag across the image to pick a pixel. The magnifier shows nearby pixels. Arrow keys move one pixel; hold Shift to move ten.",
    "workspace.x_from_left_595135": "X (from left)",
    "workspace.y_from_top_a5588e": "Y (from top)",
    "workspace.image_view_d40257": "Image view",
    "workspace.fit_image_294736": "Fit image",
    "workspace.actual_pixels_100_715803": "Actual pixels (100%)",
    "workspace.palette_colors_d752a8": "Palette colors",
    "workspace.pixel_coordinates_start_a0be66":
      "Pixel coordinates start at zero. Animated files use the first frame. Palette shares are approximate and exclude transparent pixels.",
    "workspace.clear_image_20231a": "Clear image",
    "workspace.pixel_and_palette_bbec59": "Pixel and palette",
    "workspace.approximate_dominant_palette_a73fe0": "Approximate dominant palette",
    "workspace.this_image_is_65cf49": "This image is fully transparent; it has no visible palette.",
  },
  toolId: "devtools.image-color-picker",
  app: "devtools",
  category: "color-design-tools",
  name: "Image Color Picker",
  description: "Pick exact pixel colors and extract a palette from an image locally.",
  keywords: ["image", "color", "picker", "palette", "pixel", "hex"],
  outputLanguage: "css",
  input: {
    kind: "files",
    label: "Image",
    accept: "image/png,image/jpeg,image/webp,image/gif",
    multiple: false,
    maxFiles: 1,
    maxBytes: 20 * 1024 * 1024,
    engine: "image",
    inspect: false,
  },
  settings: {
    fields: {
      x: { kind: "number", label: "Pixel X", default: 0, min: 0, max: 24_000_000 },
      y: { kind: "number", label: "Pixel Y", default: 0, min: 0, max: 24_000_000 },
      colors: { kind: "number", label: "Palette colors", default: 6, min: 3, max: 12 },
    },
  },
  trigger: { mode: "live", debounceMs: 80 },
  capabilities: { copy: true, download: true },
  workbenchMark: { text: "IMG" },
  labels: {
    empty: "Choose an image to sample its colors.",
    ready: "Pixel color and palette are ready.",
    running: "Reading image colors…",
  },
  content: {
    howToUse: [
      "Choose or drop a PNG, JPEG, WebP, or GIF image. Processing stays in your browser.",
      "Click or drag across the image to sample pixels live. Use the magnifier for precision, arrow keys to move the selection, or enter zero-based X/Y coordinates.",
      "Copy the selected HEX, RGB, or HSL value. Copy or download the extracted palette as CSS variables.",
    ],
    limitations: [
      "Images are limited to 20 MB and 24 million pixels. Animated files use their first frame.",
      "The palette is approximate: it uses a 256-pixel thumbnail, groups similar colors, and weights partially transparent pixels by alpha. Fully transparent pixels are excluded.",
      "Selected pixel values are taken from the browser-decoded sRGB image, so embedded image profiles may be converted by the browser.",
    ],
  },
} as const satisfies ToolSpec;
