import type { ToolSpec } from "../../lib/tool-framework/spec";

export default {
  toolId: "devtools.open-graph-preview",
  app: "devtools",
  category: "developer-generators",
  keywords: ["open graph", "og tags", "social card", "preview", "meta tags", "twitter card", "link preview"],
  name: "Open Graph Preview",
  description: "Preview a website’s social sharing cards and inspect its Open Graph metadata.",
  input: {
    kind: "fields",
    label: "Website URL",
    fields: [
      { channel: "text", label: "Website URL", placeholder: "https://example.com", required: true, maxLength: 2048 },
    ],
  },
  settings: { fields: {} },
  trigger: { mode: "manual", actionLabel: "Scan URL" },
  capabilities: { network: true, cancel: true, copy: true, download: true },
  workbenchMark: { text: "OG", tone: "accent" },
  labels: {
    result: "Social previews",
    empty: "Enter a public website URL to inspect its sharing metadata.",
    ready: "Social previews and metadata checks are ready.",
    running: "Fetching the page and its sharing image…",
  },
  messages: {
    "checks.titleFound": "Open Graph title found",
    "checks.usingTitle": "Using the page title",
    "checks.noTitle": "No title found",
    "checks.addTitle": "Add og:title to control the shared title explicitly.",
    "checks.addAnyTitle": "Add og:title or a document title.",
    "checks.descriptionFound": "Open Graph description found",
    "checks.descriptionMissing": "Open Graph description missing",
    "checks.usingDescription": "The preview uses the standard meta description.",
    "checks.addDescription": "Add og:description to explain the shared page.",
    "checks.imageFound": "Open Graph image found",
    "checks.imageMissing": "Usable Open Graph image missing",
    "checks.addImage": "Add an HTTP(S) og:image URL that social crawlers can access.",
    "checks.urlFound": "Open Graph URL found",
    "checks.urlMissing": "Open Graph URL missing or invalid",
    "checks.usingUrl": "The preview uses the canonical URL or fetched page address.",
    "checks.typeFound": "Open Graph type found",
    "checks.typeMissing": "Open Graph type missing",
    "checks.addType": 'Add og:type, usually "website" or "article".',
    "checks.cardFound": "X card type found",
    "checks.cardMissing": "X card type missing or unsupported",
    "checks.addCard": "Add twitter:card to choose a summary or large-image card.",
    "checks.duplicateTags": "Duplicate {property} tags",
    "checks.duplicateValues":
      "Found {count, number} values. This preview uses the first nonempty value; platforms may choose differently.",
    "checks.dimensionsMissing": "Image dimensions not declared",
    "checks.addDimensions":
      "Add og:image:width and og:image:height. Declared dimensions are not a measurement of the downloaded image.",
    "checks.imageUnavailable": "Image preview unavailable",
    "checks.imageTimedOut": "The image could not be downloaded within the preview time limit.",
    "errors.publicUrl": "Enter a public website URL or domain.",
    "errors.responseTooLarge": "The remote response is too large to preview.",
    "errors.unsupportedEncoding": "The page uses an unsupported content encoding.",
    "errors.addressUnresolved": "The website's address could not be resolved.",
    "errors.privateAddress": "Only public websites can be inspected.",
    "errors.tooManyRedirects": "The website redirects too many times.",
    "errors.invalidRedirect": "The website returned an invalid redirect.",
    "errors.httpRejected": "The website returned HTTP {status}. It may block automated previews.",
    "errors.retryPublicPage": "Try another public page or retry later.",
    "errors.notHtml": "This URL does not return an HTML page.",
    "errors.unsupportedImage": "The preview image is not a supported raster image.",
    "errors.timeout": "The website took too long to respond. Try again.",
    "errors.unreachable": "The website could not be reached securely. Check its URL and try again.",
    "errors.imageFormatMismatch": "The image response does not match its declared format.",
    "workspace.metadataChecks": "Metadata checks",
    "workspace.scannedUrl": "Scanned URL",
    "workspace.redirectedFrom": "Redirected from",
    "workspace.sharingImage": "Sharing image",
    "workspace.websiteUrl": "Website URL",
    "workspace.cancel": "Cancel",
    "workspace.editUrl": "Edit URL",
    "workspace.socialPreviews": "Social previews",
    "workspace.previewPlatform": "Preview platform",
    "workspace.htmlTags": "HTML tags",
    "workspace.fetchedHtmlTags": "Fetched HTML tags",
    "workspace.afterAScanCheckWhichMetadataIs":
      "After a scan, check which metadata is present and what needs attention.",
    "workspace.metadataInspector": "Metadata inspector",
    "workspace.socialImage": "Social sharing image",
    "workspace.imageUnavailable": "Image preview unavailable",
    "workspace.noImage": "No sharing image found",
    "workspace.noTitle": "No title found",
    "workspace.linkPreview": "{platform} link preview",
    "workspace.passedCheck": "Passed",
    "workspace.warningCheck": "Warning",
    "workspace.errorCheck": "Error",
    "workspace.imageSize": "Declared size: {width, number} × {height, number}",
    "errors.invalid-url":
      "Enter a valid public website URL or domain, such as slack.com. Credentials and custom ports are not supported.",
    "workspace.rescan": "Rescan",
    "workspace.scan": "Scan URL",
    "workspace.fetching": "Fetching the page and checking its social metadata…",
    "workspace.startHelp": "Enter a public website URL above, then scan it to see how its links could appear.",
    "workspace.failed": "Could not scan this page",
    "workspace.scanning": "Scanning website",
    "workspace.previewLink": "Preview a shared link",
    "workspace.approximatePreview":
      "Approximate {platform} preview. Actual appearance may vary with platform caching and layout.",
    "workspace.errorCount": "{count, plural, one {# error} other {# errors}}",
    "workspace.warningCount": "{count, plural, one {# warning} other {# warnings}}",
    "workspace.passedCount": "{count, number} passed",
  },
  content: {
    howToUse: [
      "Enter a public website URL or domain such as slack.com, then select Scan URL. Domains without a protocol use HTTPS.",
      "Switch between Facebook, X, LinkedIn, WhatsApp, and Discord to preview the fetched title, description, and image.",
      "Review the metadata inspector for missing tags and image issues. The HTML tags tab lets you copy or download the metadata found on the page.",
      "After updating your website, select Rescan to fetch it again.",
    ],
    limitations: [
      "Previews approximate each platform’s layout. Platforms may crop images differently or continue displaying cached metadata.",
      "The scanner reads the HTML returned by the website without running JavaScript. Login-only pages and sites that block automated requests cannot be inspected.",
      "Only public HTTP and HTTPS addresses on their standard ports are supported. Scans follow up to five redirects and limit page and image sizes.",
      "Your submitted URL and any sharing image URLs are fetched by our server. The destination websites receive those requests; browser cookies and login credentials are not forwarded.",
    ],
    faq: [
      {
        q: "Do I need to enter a title or description?",
        a: "No. The scanner extracts existing Open Graph and Twitter tags from your page, with the HTML title and meta description as fallbacks.",
      },
      {
        q: "Does this tool generate new meta tags?",
        a: "It inspects tags already on your website. Use Meta Tag Generator to create tags for a new page.",
      },
      {
        q: "Why does a platform still show my old preview?",
        a: "Social platforms cache their own previews. Rescanning here checks the current page but does not clear another platform’s cache.",
      },
      {
        q: "Why is the sharing image unavailable?",
        a: "The image may be missing, blocked, too large, or an unsupported format. The inspector keeps the original image URL and explains fetch failures.",
      },
    ],
    examples: [{ label: "Inspect Slack", text: "https://slack.com" }],
  },
} as const satisfies ToolSpec;
