import { COLOR_MESSAGES } from "../../lib/devtools/shared/color-messages.ts";
import type { ToolSpec } from "../../lib/tool-framework/spec";

export default {
  messages: {
    ...COLOR_MESSAGES,
    "workspace.shadow_preview_ea1c1a": "Shadow preview",
    "workspace.reset_daee76": "Reset",
    "workspace.object_with_the_1ac233": "Object with the generated box shadow",
    "workspace.use_this_shadow_2aebea": "Use this shadow",
    "workspace.css_b581e4": "CSS",
    "workspace.preset_7252e7": "Preset",
    "workspace.choose_a_starting_a136fd": "Choose a starting point",
    "workspace.layers_d9472d": "Layers · ",
    "workspace.add_9fd728": "Add",
    "workspace.layer_9d663a": "Layer ",
    "workspace.inset_5b9b96": " · inset",
    "workspace.editing_fab453": "Editing",
    "workspace.selected_shadow_color_fee0dd": "Selected shadow color",
    "workspace.offset_b1a1e8": "Offset",
    "workspace.inset_shadow_3baaef": "Inset shadow",
    "workspace.preview_colors_710006": "Preview colors",
    "workspace.background_ea2b8a": "Background",
    "workspace.object_62a6da": "Object",
    "workspace.advanced_css_layers_291360": "Advanced CSS layers",
    "workspace.additional_layers_3940c3": "Additional layers",
    "workspace.one_shadow_per_987f6b":
      "One shadow per line. Use two to four pixel lengths, optional inset, and HEX or comma-separated rgb()/rgba().",
    "workspace.use_first_enabled_318bdf": "Use first enabled layer opacity for extra rgba() layers",
    "workspace.include_webkit_prefix_f1ba8a": "Include WebKit prefix",
    "workspace.drag_handles_or_a9f0bc":
      "Drag handles or press Space, use arrow keys, and press Space again to reorder layers.",
    "workspace.shadowLayers": "Shadow layers",
    "workspace.shadowLayer": "Shadow layer {number}",
    "workspace.reorderLayer": "Reorder shadow layer {number}",
    "workspace.enableLayer": "Enable shadow layer {number}",
    "workspace.editLayer": "Edit shadow layer {number}",
    "workspace.removeLayer": "Remove shadow layer {number}",
    "workspace.horizontalOffset": "Horizontal offset value",
    "workspace.verticalOffset": "Vertical offset value",
    "workspace.lengths.blur": "Blur",
    "workspace.lengths.spread": "Spread",
    "workspace.presets.Soft": "Soft",
    "workspace.presets.Layered": "Layered",
    "workspace.presets.Inset": "Inset",
    "workspace.presets.Hard": "Hard",
    "workspace.layerCount": "Layers {count}/12",
    "workspace.layerName": "Layer {number}{inset, select, yes { (inset)} other {}}",
  },
  toolId: "devtools.css-box-shadow",
  sharing: { version: 1 },
  // `slugFromName("CSS Box Shadow Generator")` is "css-box-shadow-generator",
  // but the live indexed URL is /devtools/css-box-shadow and a slug is frozen
  // at first insert — so it is declared explicitly rather than derived.
  slug: "css-box-shadow",
  app: "devtools",
  category: "color-design-tools",
  keywords: ["box-shadow", "css", "shadow", "elevation", "inset", "blur", "spread", "generator"],
  name: "CSS Box Shadow Generator",
  description: "Generate a CSS box-shadow declaration.",
  outputLanguage: "css",
  input: {
    kind: "fields",
    label: "Shadow Color",
    fields: [
      {
        channel: "text",
        label: "HEX color",
        placeholder: "#00000080",
        required: true,
        multiline: false,
      },
    ],
  },
  settings: {
    fields: {
      layers: { kind: "textarea", label: "Visual shadow layers", default: "", help: "Visual layer editor data." },
      previewBackground: { kind: "color", label: "Preview background", default: "#f1f5f9", allowTransparent: true },
      previewObject: { kind: "color", label: "Object color", default: "#ffffff", allowTransparent: true },
      x: {
        kind: "number",
        label: "X offset",
        help: "Horizontal distance in pixels. Positive moves the shadow right.",
        default: 0,
        min: -100,
        max: 100,
        suffix: "px",
        pane: "main",
      },
      y: {
        kind: "number",
        label: "Y offset",
        help: "Vertical distance in pixels. Positive moves the shadow down.",
        default: 12,
        min: -100,
        max: 100,
        suffix: "px",
        pane: "main",
      },
      blur: {
        kind: "number",
        label: "Blur",
        help: "Larger values give a softer, more diffuse edge.",
        default: 30,
        min: 0,
        max: 200,
        suffix: "px",
        pane: "main",
      },
      spread: {
        kind: "number",
        label: "Spread",
        help: "Grows or shrinks the shadow before blurring. Negative values pull it in under the element.",
        default: -8,
        min: -100,
        max: 100,
        suffix: "px",
        pane: "main",
      },
      inset: {
        kind: "toggle",
        label: "Inset",
        help: "Draws the shadow inside the element instead of behind it.",
        default: false,
      },
      additionalLayers: {
        kind: "textarea",
        label: "Additional shadow layers",
        help: "Add one shadow per line using 0/px lengths and an optional HEX or rgb() color.",
        default: "",
        rows: 4,
        pane: "main",
        span: "full",
      },
      linkOpacity: {
        kind: "toggle",
        label: "Link opacity",
        help: "Apply the input HEX alpha to rgba() colors in additional layers.",
        default: false,
      },
      showBrowserPrefixes: {
        kind: "toggle",
        label: "Show browser prefixes",
        help: "Include a -webkit-box-shadow declaration before the standard one.",
        default: false,
      },
    },
  },
  trigger: { mode: "live", debounceMs: 120 },
  capabilities: { copy: true, download: true },
  workbenchMark: { text: "SHDW" },
  labels: {
    empty: "Enter a HEX shadow color to build a CSS box-shadow declaration.",
    ready: "CSS box-shadow declaration is ready.",
    running: "Building box shadow…",
  },
  content: {
    howToUse: [
      "Enter the shadow colour as a hex value. `#RRGGBBAA` gives you a translucent shadow, which is almost always what you want — a fully opaque shadow reads as a hard outline.",
      "Adjust the offsets, blur, and spread; add one extra shadow layer per line when a single elevation is not enough.",
      "A believable elevation usually means a small Y offset, a blur two to three times that offset, and a slightly negative spread. Copy the declaration when it looks right.",
    ],
    limitations: [
      "Additional layers accept two to four 0/px lengths, optional inset, and an optional HEX or comma-separated rgb()/rgba() colour.",
      "Lengths are pixels only — no rem, em, or percentage units.",
      "Visual layers accept HEX, supported CSS names, rgb(), and hsl(). Advanced text layers accept HEX or comma-separated rgb()/rgba().",
      "Use up to 12 visual layers and up to 20 advanced text layers.",
      "This produces `box-shadow`, not `filter: drop-shadow()` — the two differ on transparent PNGs and non-rectangular shapes.",
    ],
    faq: [
      {
        q: "What is the difference between blur and spread?",
        a: "Spread resizes the shadow's shape before it is blurred; blur softens its edge. A negative spread with a large blur is the usual recipe for a soft, grounded elevation.",
      },
      {
        q: "How do I stack two shadows?",
        a: "Keep the generated first layer, then add the second complete shadow value on a new line under Additional shadow layers.",
      },
      {
        q: "Why does inset look like nothing happened?",
        a: "An inset shadow draws inside the padding box, so it is hidden if the element has no background or if the offsets are too small to clear the edge. Increase the offset or blur.",
      },
      {
        q: "Can I use a CSS variable for the colour?",
        a: "Not as input — it has to be a hex value so it can be validated. Swap the literal for `var(--shadow-color)` in the generated declaration afterwards.",
      },
    ],
    examples: [
      {
        label: "Slate elevation",
        text: "#0f172a",
        settings: { layers: "", additionalLayers: "", x: 0, y: 12, blur: 30, spread: -8, inset: false },
      },
    ],
  },
} as const satisfies ToolSpec;
