import type { ToolSpec } from "../../lib/tool-framework/spec";

export default {
  toolId: "devtools.color-picker",
  app: "devtools",
  category: "color-design-tools",
  keywords: [
    "color",
    "picker",
    "hex",
    "rgb",
    "hsl",
    "hsv",
    "hsb",
    "hwb",
    "cmyk",
    "lab",
    "oklch",
    "p3",
    "convert",
    "alpha",
  ],
  name: "Color Picker",
  description: "Pick a color visually, adjust transparency, and copy HEX, RGB, HSL, HSV, CMYK, and more.",
  layout: "stacked",
  input: {
    kind: "fields",
    label: "Color",
    fields: [
      {
        channel: "text",
        label: "Color",
        placeholder: "#2563eb",
        required: true,
        multiline: false,
      },
    ],
  },
  settings: {
    fields: {
      normalizeShorthand: {
        kind: "toggle",
        label: "Normalize shorthand",
        help: "Expand #RGB and #RGBA output to their full channel forms.",
        default: true,
      },
      legacyRgbCommas: {
        kind: "toggle",
        label: "Legacy RGB commas",
        help: "Use comma-separated rgb() and rgba() syntax instead of CSS space syntax.",
        default: true,
      },
      includeHsl: {
        kind: "toggle",
        label: "Include HSL",
        help: "Include the equivalent HSL value when showing all formats.",
        default: true,
      },
      outputFormat: {
        kind: "select",
        label: "Output format",
        help: "Show all formats or choose one. HSV/HSB and CMYK are numeric design values, not CSS. CMYK is an unprofiled print approximation.",
        default: "all",
        choices: [
          { label: "All formats", value: "all" },
          { label: "HEX", value: "hex" },
          { label: "RGB", value: "rgb" },
          { label: "HSL", value: "hsl" },
          { label: "HSV / HSB", value: "hsv" },
          { label: "HWB", value: "hwb" },
          { label: "CMYK", value: "cmyk" },
          { label: "Lab", value: "lab" },
          { label: "LCH", value: "lch" },
          { label: "OKLab", value: "oklab" },
          { label: "OKLCH", value: "oklch" },
          { label: "XYZ D65", value: "xyz-d65" },
          { label: "XYZ D50", value: "xyz-d50" },
          { label: "sRGB", value: "srgb" },
          { label: "Linear sRGB", value: "srgb-linear" },
          { label: "Display P3", value: "display-p3" },
          { label: "A98 RGB", value: "a98-rgb" },
          { label: "ProPhoto RGB", value: "prophoto-rgb" },
          { label: "Rec.2020", value: "rec2020" },
        ],
        pane: "main",
      },
    },
  },
  trigger: { mode: "live", debounceMs: 150 },
  capabilities: { copy: true },
  workbenchMark: { text: "PICK" },
  labels: {
    empty: "Pick a color or enter HEX, RGB, HSL, or a CSS color name.",
    ready: "Color values are ready.",
    running: "Updating color values…",
  },
  content: {
    howToUse: [
      "Choose a color visually, move the hue/saturation/lightness controls, or paste HEX, RGB, HSL, or a CSS color name.",
      "Choose All formats or a specific output: HEX, RGB, HSL, HSV/HSB, HWB, CMYK, Lab, LCH, OKLab, OKLCH, XYZ, or RGB color spaces including Display P3.",
      "Values update as you type. Alpha is preserved in every output; transparent colors use `rgba()` or `hsla()` with legacy syntax, or an alpha component in other formats.",
      "Adjust opacity and copy the format your target needs. Recent colors remain available during this visit.",
    ],
    limitations: [
      "Standalone HEX, RGB, HSL, named colors, and transparent are supported. Stylesheet-dependent variables and currentColor are not resolved.",
      "HEX output is uppercase and cannot be switched to lowercase.",
      "HSL uses three decimal places; converting arbitrary fractional RGB values to HEX quantizes channels to eight bits.",
      "Input and the visual picker use sRGB. Other color spaces are converted outputs; their notation is not accepted as input, and conversion does not add colors outside the source gamut.",
      "HSV and HSB name the same model. HSV/HSB and CMYK output are numeric design values, not CSS color functions.",
      "CMYK is an unprofiled approximation. Print results depend on the printer, ink, paper, and color profile.",
      "RGB and HSL alpha use up to three decimal places; other CSS outputs use up to six. HEX alpha is quantized to eight bits.",
    ],
    faq: [
      {
        q: "Can I enter an `rgb()` or a colour name?",
        a: "Yes. Paste RGB, HSL, any standard CSS color name, or transparent alongside the four HEX forms.",
      },
      {
        q: "Why is the HSL lightness misleading?",
        a: "HSL lightness is a geometric average of the RGB channels, not perceived brightness. Pure yellow and pure blue are both 50% lightness but look nothing alike.",
      },
      {
        q: "How is transparency handled?",
        a: "An 8-digit (or 4-digit) HEX carries alpha, as do RGB and HSL inputs with alpha. Every output preserves transparency; legacy RGB and HSL output use `rgba()` and `hsla()` for transparent colors.",
      },
    ],
    examples: [
      { label: "Six-digit HEX", text: "#3366ff" },
      { label: "With alpha", text: "#3366ff80" },
      { label: "Shorthand", text: "#f0c" },
    ],
  },
} as const satisfies ToolSpec;
