import { COLOR_MESSAGES } from "../../lib/devtools/shared/color-messages.ts";
import type { ToolSpec } from "../../lib/tool-framework/spec";
export default {
  toolId: "devtools.palette-generator",
  sharing: { version: 1 },
  app: "devtools",
  category: "color-design-tools",
  name: "Palette Generator",
  description: "Build harmonious color palettes, keep your favorites, and export reusable color tokens.",
  keywords: ["palette", "color", "scheme", "harmony", "tokens", "swatches"],
  input: { kind: "none" },
  outputLanguage: "css",
  settings: {
    fields: {
      seed: { kind: "text", label: "Starting color", default: "#3366FF", maxLength: 200 },
      harmony: {
        kind: "select",
        label: "Harmony",
        default: "analogous",
        choices: [
          { label: "Analogous", value: "analogous" },
          { label: "Complementary", value: "complementary" },
          { label: "Triadic", value: "triadic" },
          { label: "Monochromatic", value: "monochromatic" },
        ],
      },
      count: { kind: "number", label: "Colors", default: 5, min: 2, max: 10 },
      variation: { kind: "number", label: "Variation", default: 0, min: 0 },
      colors: { kind: "textarea", label: "Palette colors", default: "" },
      format: {
        kind: "select",
        label: "Export format",
        default: "css",
        choices: [
          { label: "CSS variables", value: "css" },
          { label: "JSON", value: "json" },
          { label: "SVG swatches", value: "svg" },
        ],
      },
    },
  },
  trigger: { mode: "live", debounceMs: 100 },
  capabilities: { copy: true, download: true },
  workbenchMark: { text: "PAL" },
  labels: { empty: "Choose a starting color.", ready: "Palette is ready.", running: "Updating palette…" },
  messages: {
    "palette.name": "Name",
    "palette.color": "Color",
    ...COLOR_MESSAGES,
    "workspace.generateVariation": "Generate variation",
    "workspace.yourPalette": "Your palette",
    "workspace.buildAPalette": "Build a palette",
    "workspace.paletteSwatches": "Palette swatches",
    "workspace.selectAColorToEditClickHex": "Select a color to edit · Click HEX to copy · Lock colors to keep them",
    "workspace.paletteColors": "Palette colors",
    "workspace.clickToEditDragToReorderOr": "Click to edit. Drag to reorder, or use the handle below.",
    "workspace.dragToReorderOrPressSpaceArrow": "Drag to reorder, or press Space, arrow keys, then Space.",
    "workspace.checkContrast": "Check contrast ↗",
    "workspace.exportPalette": "Export palette",
    "workspace.startingColor": "Starting color",
    "workspace.harmony": "Harmony",
    "workspace.colors2": "Colors",
    "workspace.exportFormat": "Export format",
    "workspace.cssVariables": "CSS variables",
    "workspace.json": "JSON",
    "workspace.svgSwatches": "SVG swatches",
    "workspace.checkColors": "Check your colors.",
    "errors.palette": "Use 2–10 valid colors with unique IDs. Reset to generate a new palette.",
    "errors.count": "Choose 2–10 colors.",
    "errors.locked-color": "Unlock later colors before reducing the palette size.",
    "errors.harmony": "Choose a supported color harmony.",
    "errors.variation": "Variation must be a non-negative integer.",
    "workspace.paletteCount": "{count, plural, one {# color} other {# colors}} · {locked, number} locked",
    "workspace.editColor": "Edit {color}",
    "workspace.copyColor": "Copy {color}",
    "workspace.reorderColor": "Reorder {color}",
    "workspace.lockColor": "{action, select, unlock {Unlock} other {Lock}} {color}",
    "workspace.invalid": "Invalid",
    "workspace.unlockColor": "Unlock color",
    "workspace.keepColor": "Keep this color when generating",
    "workspace.selectedHint": "{number} selected · Edit in the right panel",
    "workspace.selectColor": "Select a color to edit",
    "workspace.minimumCount": "Unlock later swatches to use fewer than {count, number} colors.",
    "workspace.selectedColor": "Selected color · {number, number}",
    "workspace.harmonyValue.analogous": "Analogous",
    "workspace.harmonyValue.complementary": "Complementary",
    "workspace.harmonyValue.triadic": "Triadic",
    "workspace.harmonyValue.monochromatic": "Monochromatic",
  },
  content: {
    howToUse: [
      "Choose a starting color and harmony, then generate a palette of 2–10 colors.",
      "Select any swatch to edit it. Lock colors you want to keep when generating another variation.",
      "Drag the handles to change the order, or focus a handle and press Space, arrow keys, then Space.",
      "Copy CSS variables, or download CSS, JSON, or an SVG swatch sheet.",
    ],
    limitations: [
      "Harmonies use the HSL color wheel. A pleasing palette does not guarantee readable text; check intended pairs in Contrast Checker.",
    ],
    relatedToolIds: ["devtools.contrast-checker", "devtools.image-color-picker", "devtools.gradient-generator"],
  },
} as const satisfies ToolSpec;
