import type { ToolSpec } from "../../lib/tool-framework/spec";

const unitChoices = ["px", "rem", "em", "pt", "%", "vw", "vh", "vmin", "vmax"].map((value) => ({
  label: value,
  value,
}));

export default {
  messages: {
    "css.unit": "Choose a supported CSS unit.",
    "css.precision": "Precision must be a whole number from 0 to 12.",
    "css.numberRequired": "Enter a number, optionally followed by a supported CSS unit.",
    "css.finiteNumber": "The value is too large; enter a finite number.",
    "css.overflow": "The converted value is too large. Reduce the value or its reference size.",
    "css.valueRequired": "Enter a CSS value to convert.",
    "css.positiveReference":
      "{reference, select, root {Root font size} parent {Parent font size} element {Element font size} percentage {Percentage reference length} width {Viewport width} height {Viewport height} other {Reference}} must be a finite, positive number.",
    "css.failed": "Could not convert this value.",
    "css.converted": "{converted, number} converted · {corrections, number} need correction",
    "css.columns.line": "Line",
    "css.columns.input": "Input",
    "css.columns.result": "Result",
    "css.columns.formula": "Formula",
    "workspace.convert_css_values_50a491": "Convert CSS values",
    "workspace.from_218197": "From",
    "workspace.swap_units_8104cc": "Swap units",
    "workspace.to_f4b06e": "To",
    "workspace.values_53b09e": "Values",
    "workspace.one_value_per_dc46f4": "One value per line. A unit suffix overrides From for that value.",
    "workspace.em_reference_bef2dc": "em reference",
    "workspace.element_spacing_and_c30723": "Element (spacing and sizes)",
    "workspace.parent_font_size_c13498": "Parent (font-size)",
    "workspace.percentage_reference_14b5c0": "Percentage reference",
    "workspace.parent_font_size_d6ad58": "Parent font size",
    "workspace.explicit_reference_length_f7beb3": "Explicit reference length",
    "workspace.decimal_places_004a34": "Decimal places",
    "workspace.include_calculation_a40841": "Include calculation",
    "workspace.percentages_depend_on_683f68":
      "Percentages depend on the CSS property. Viewport units use the dimensions you supply. Negative values may not be allowed by your target property.",
    "workspace.converted_values_b10d04": "Converted values",
    "workspace.conversionContext": "Conversion context",
    "workspace.rootFontSize": "Root font size",
    "workspace.remReference": "rem is relative to the root element.",
    "workspace.elementFontSize": "Element font size",
    "workspace.elementReference": "Use the element’s computed font size for em lengths.",
    "workspace.referenceLength": "100% reference length",
    "workspace.actualReference":
      "Supply the actual reference for the CSS property, such as the containing block width.",
    "workspace.parentFontSize": "Parent font size",
    "workspace.parentReference": "Reference for font-size in em or percent.",
    "workspace.viewportWidth": "Viewport width",
    "workspace.viewportHeight": "Viewport height",
  },
  toolId: "devtools.css-unit-converter",
  sharing: { version: 1 },
  app: "devtools",
  category: "color-design-tools",
  keywords: ["css", "px", "rem", "em", "pt", "percent", "viewport", "unit", "convert"],
  name: "CSS Unit Converter",
  description: "Convert CSS lengths with explicit font, percentage and viewport references.",
  input: {
    kind: "fields",
    label: "CSS values",
    fields: [{ channel: "text", label: "Values", placeholder: "16px\n2rem\n50%", required: true, multiline: true }],
  },
  settings: {
    fields: {
      from: { kind: "select", label: "From", default: "px", choices: unitChoices },
      to: { kind: "select", label: "To", default: "rem", choices: unitChoices },
      base: {
        kind: "number",
        label: "Root font size",
        help: "rem uses the computed font size of the root element.",
        default: 16,
        min: 0.01,
        max: 10000,
        suffix: "px",
      },
      elementFontSize: { kind: "number", label: "Element font size", default: 16, min: 0.01, max: 10000, suffix: "px" },
      parentFontSize: { kind: "number", label: "Parent font size", default: 16, min: 0.01, max: 10000, suffix: "px" },
      emContext: {
        kind: "select",
        label: "em reference",
        default: "element",
        choices: [
          { label: "Element (spacing and sizes)", value: "element" },
          { label: "Parent (font-size)", value: "parent" },
        ],
      },
      percentageReference: {
        kind: "select",
        label: "Percentage reference",
        default: "parent-font",
        choices: [
          { label: "Parent font size", value: "parent-font" },
          { label: "Explicit reference length", value: "length" },
        ],
      },
      percentageBase: {
        kind: "number",
        label: "Reference length",
        help: "The pixel length represented by 100%, such as the containing block width.",
        default: 100,
        min: 0.01,
        max: 100000,
        suffix: "px",
      },
      viewportWidth: { kind: "number", label: "Viewport width", default: 1366, min: 1, max: 100000, suffix: "px" },
      viewportHeight: { kind: "number", label: "Viewport height", default: 768, min: 1, max: 100000, suffix: "px" },
      precision: { kind: "number", label: "Decimal places", default: 6, min: 0, max: 12, step: 1 },
      roundResults: {
        kind: "toggle",
        label: "Use four decimal places",
        help: "Compatibility setting for saved conversions; changing precision turns it off.",
        default: false,
      },
      includeFormula: { kind: "toggle", label: "Include formula", default: false },
    },
  },
  trigger: { mode: "live" },
  capabilities: { copy: true },
  workbenchMark: { text: "UNIT" },
  labels: {
    empty: "Enter a CSS value to convert.",
    ready: "Converted CSS values are ready.",
    running: "Converting CSS units…",
  },
  content: {
    howToUse: [
      "Enter a number or paste a value with its unit. Use one value per line for a batch; a suffix overrides the From unit for that line.",
      "Choose the target unit and the relevant font, percentage or viewport references. rem uses the root font; em uses the element font, except when converting font-size itself, which uses the parent.",
      "Copy the result. Set decimal precision or include the calculation; invalid batch rows are reported without discarding valid conversions.",
    ],
    limitations: [
      "Percentages depend on the CSS property. Choose parent font size for font-size, or supply the actual reference length for a size; this tool cannot infer page layout.",
      "Viewport units use the dimensions supplied here. Dynamic and small viewport variants, ch/ex, expressions such as calc(), and CSS variables are not evaluated.",
      "Negative numbers are converted mathematically; whether a negative value is valid depends on the CSS property where you use it.",
    ],
    faq: [
      {
        q: "Why do rem and em give different results?",
        a: "rem always uses the root element's font size. em uses the element's own font size for lengths, or the parent's font size when setting font-size.",
      },
      {
        q: "What does 100% mean?",
        a: "It means the selected reference: the parent font size, or an explicit pixel length. The correct reference depends on the CSS property.",
      },
    ],
    examples: [
      { label: "32px in rem", text: "32" },
      { label: "Mixed units", text: "16px\n2rem\n12pt" },
    ],
  },
} as const satisfies ToolSpec;
