import type { ToolSpec } from "../../lib/tool-framework/spec";

export default {
  toolId: "media.crop-image",
  app: "media",
  category: "image-editing",
  keywords: [
    "crop",
    "image",
    "trim",
    "aspect ratio",
    "jpg",
    "png",
    "webp",
    "cut",
  ],
  name: "Crop Image",
  description: "Drag independent points to crop an image, or use a rectangular crop.",
  optionsPanel: { collapsible: false, layout: "grid" },
  layout: "stacked",
  input: {
    kind: "files",
    label: "Source image",
    accept: "image/jpeg,image/png,image/webp",
    multiple: false,
    engine: "image",
    maxBytes: 26_214_400,
    maxTotalBytes: 104_857_600,
  },
  settings: {
    fields: {
      cropMode: {
        kind: "select",
        label: "Crop mode",
        default: "freeform",
        choices: [
          { label: "Freeform points", value: "freeform" },
          { label: "Rectangle", value: "rectangle" },
        ],
      },
      cropPointCount: { kind: "number", label: "Freeform point count", default: 4, min: 3, max: 12, step: 1 },
      cropPoints: { kind: "text", label: "Crop points", default: "", maxLength: 2048 },
      cropAspect: {
        kind: "select",
        span: "full",
        label: "Aspect ratio",
        help: "Locks the drag handles in the preview. Typing a width or height directly releases the lock.",
        default: "free",
        choices: [
          { label: "Free", value: "free" },
          { label: "1:1", value: "1:1" },
          { label: "4:3", value: "4:3" },
          { label: "16:9", value: "16:9" },
        ],
      },
      cropX: {
        kind: "number",
        label: "X",
        help: "Distance from the left edge of the image, in pixels.",
        default: 0,
        min: 0,
        suffix: "px",
      },
      cropY: {
        kind: "number",
        label: "Y",
        help: "Distance from the top edge of the image, in pixels.",
        default: 0,
        min: 0,
        suffix: "px",
      },
      cropWidth: {
        kind: "number",
        label: "Width",
        default: 0,
        min: 0,
        suffix: "px",
      },
      cropHeight: {
        kind: "number",
        label: "Height",
        default: 0,
        min: 0,
        suffix: "px",
      },
      outputFormat: {
        kind: "select",
        span: "full",
        label: "Output format",
        help: "Original keeps the source format. Choose PNG when the image has transparency you need to keep.",
        default: "png",
        choices: [
          { label: "Original format", value: "original" },
          { label: "JPEG", value: "jpeg" },
          { label: "PNG", value: "png" },
          { label: "WebP", value: "webp" },
        ],
      },
      quality: {
        kind: "slider",
        span: "full",
        label: "Quality",
        help: "Applies to JPEG and WebP output. PNG is lossless and ignores it.",
        default: 80,
        min: 30,
        max: 100,
        suffix: "%",
      },
    },
  },
  trigger: { mode: "manual", actionLabel: "Crop image" },
  capabilities: { cancel: true, download: true, progress: true },
  workbenchMark: { text: "ICUT" },
  labels: {
    empty: "Add an image to crop.",
    ready: "Your cropped image is ready to download.",
    running: "Cropping image…",
  },
  content: {
    howToUse: [
      "Add a single JPG, PNG, or WebP. It is decoded in your browser — the image is never uploaded.",
      "In Freeform points mode, choose 3–12 points and drag each independently, or select a point and type its X and Y. Drag inside the selection to move it. Width and height show the selection bounds.",
      "Choose Rectangle mode to use an aspect ratio of 1:1, 4:3, or 16:9. Typing a width or height directly switches the ratio back to Free.",
      "Choose an output format and quality, then run the crop and download the result.",
    ],
    limitations: [
      "One image per run. Crop a batch by repeating the tool, or resize them together with a different tool.",
      "HEIC is not accepted here, because the preview cannot be rendered for it. Convert to JPG or PNG first.",
      "Freeform points stay inside the image and edges cannot cross. Output is the selection’s bounding rectangle with transparent pixels outside the polygon; this does not correct perspective.",
      "Choosing JPEG flattens transparency onto white. Keep PNG or WebP if the source has an alpha channel.",
      "Images must be 25 MiB or smaller and under 100 megapixels.",
    ],
    faq: [
      {
        q: "Where is the origin for X and Y?",
        a: "The top-left corner of the image, which is the usual convention for raster images — unlike PDFs, where it is the bottom-left.",
      },
      {
        q: "Why can I not add a HEIC file?",
        a: "The crop UI needs a live preview and browsers cannot render HEIC directly. Convert it to JPG or PNG first, then crop.",
      },
      {
        q: "Does cropping re-encode the image?",
        a: "Yes. The image is decoded, cropped, and re-encoded, so a JPEG source loses a little quality even at 100%. Choose PNG output if you need that avoided.",
      },
      {
        q: "Why did the aspect ratio reset to Free?",
        a: "Typing a width or height directly is an explicit override, so the lock is released rather than silently fighting your input.",
      },
    ],
  },
} as const satisfies ToolSpec;
